### ISSUE TITLE
REQUEST: Do not extensify (.cfg) a config file until it is ready to go active.

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScaleCompanion_PKMC#2]
_**Problem:**_ Multiple log entries of "Cannot create config from file ..."

Now, before you facepalm, I do understand why these are present in the log.  It's merely KSP complaining that it can't do what it expects it should be doing because there is nothing to do anything with.  These are simply empty config files.  But, they add unnecessary clutter to the log and with EVERYOONE just saying "forkit" it only adds a millisecond or two on every INFO & WRN ... it adds up.

_**Solution:**_ Drop the .cfg extension from files that are not currently active.  You can extensify when you are ready to implement the contents.

I am cognizant that this is your call. If you are okay with this approach, I'd be happy to do the grunt work for you.

**Comment by Lisias** [comment]
I was in a hurry, I just had realised the last TweakScale "ticket" was about the same issue I had diagnosed exactly one year ago (see [this](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-141-tweakscale-under-lisias-management-24321-2020-00804/&do=findComment&comment=3842835)), and since I already knew about what it was (essentially, it was one of the motivation for creating the whole Companion series), I was in a hurry.

Being awake on the coldest night of the year - from 20oC (68oF) two days ago to less than 5oC (~40oF) because I could not sleep didn't helped at all.

**Comment by Lisias** [comment]
Well, since we are here, I'm extending this issue on every TweakScale related patch from me.
